# Generated by Django 2.0.7 on 2018-07-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Scheduling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(max_length=30)),
                ('stylist', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
            ],
        ),
    ]
